/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import dao.AdvogadoEnderecoDAO;
import dao.AdvogadosDAO;
import dao.EnderecoDAO;
import jurisoft.Mensagens;
import regrasDeNegocio.Advogados;
import regrasDeNegocio.Endereco;
import regrasDeNegocio.AdvogadoEndereco;
import regrasDeNegocio.Letras;
import regrasDeNegocio.Numeros;
import regrasDeNegocio.ValidarCPF;

/**
 *
 * @author 00733769225
 */
public class FormCadastrarAdvogado extends javax.swing.JDialog {

    /**
     * Creates new form FormCadastrarAdvogado
     */
    public FormCadastrarAdvogado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        travarComponentes();
        
        txtNumeroEnd.setDocument(new Numeros());
        //txtCPFCli.setDocument(new Numeros());
        txtCNHAdv.setDocument(new Numeros());
        txtNomeAdv.setDocument(new Letras());
        txtNaturalidadeAdv.setDocument(new Letras());
        txtNacionalidadeAdv.setDocument(new Letras());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNomeAdv = new javax.swing.JLabel();
        txtNomeAdv = new javax.swing.JTextField();
        lblSexoAdv = new javax.swing.JLabel();
        lblNascAdv = new javax.swing.JLabel();
        txtNascAdv = new javax.swing.JFormattedTextField();
        lblEstCivilAdv = new javax.swing.JLabel();
        cmbEstCivilAdv = new javax.swing.JComboBox();
        lblCPFAdv = new javax.swing.JLabel();
        txtCPFAdv = new javax.swing.JFormattedTextField();
        lblRGAdv = new javax.swing.JLabel();
        txtRGAdv = new javax.swing.JTextField();
        lblRendaFamiliarAdv = new javax.swing.JLabel();
        lblCNHAdv = new javax.swing.JLabel();
        txtCNHAdv = new javax.swing.JTextField();
        txtNaturalidadeAdv = new javax.swing.JTextField();
        lblNaturalidadeAdv = new javax.swing.JLabel();
        txtNacionalidadeAdv = new javax.swing.JTextField();
        lblNacionalidadeAdv = new javax.swing.JLabel();
        lblTelefoneAdv = new javax.swing.JLabel();
        txtTelefoneAdv = new javax.swing.JFormattedTextField();
        lblTelefone2Adv = new javax.swing.JLabel();
        txtTelefone2Adv = new javax.swing.JFormattedTextField();
        lblEmailAdv = new javax.swing.JLabel();
        txtEmailAdv = new javax.swing.JTextField();
        lblDataCadastroAdv = new javax.swing.JLabel();
        txtDataCadastroAdv = new javax.swing.JFormattedTextField();
        lblDadosAdv = new javax.swing.JLabel();
        lblEnderecoAdv = new javax.swing.JLabel();
        lblRuaEnd = new javax.swing.JLabel();
        txtRuaEnd = new javax.swing.JTextField();
        lblNumeroEnd = new javax.swing.JLabel();
        txtNumeroEnd = new javax.swing.JTextField();
        lblBairroEnd = new javax.swing.JLabel();
        txtBairroEnd = new javax.swing.JTextField();
        lblUFEnd = new javax.swing.JLabel();
        cmbUFEnd = new javax.swing.JComboBox();
        lblCidadeEnd = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        cmbSexoAdv = new javax.swing.JComboBox();
        txtCidadeEnd = new javax.swing.JTextField();
        txtRendaFamiliarAdv = new javax.swing.JTextField();
        lblOAB = new javax.swing.JLabel();
        lblInscricaoAdv = new javax.swing.JLabel();
        lblLetraAdv = new javax.swing.JLabel();
        lblSecAdv = new javax.swing.JLabel();
        lblTipoInscAdv = new javax.swing.JLabel();
        lblDataInscricaoOABAdv = new javax.swing.JLabel();
        cmbSecAdv = new javax.swing.JComboBox();
        txtInscricaoAdv = new javax.swing.JTextField();
        cmbLetraAdv = new javax.swing.JComboBox<>();
        cmbTipoInscAdv = new javax.swing.JComboBox<>();
        txtDataInscricaoOABAdv = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(1054, 96));
        jPanel1.setMinimumSize(new java.awt.Dimension(1054, 96));
        jPanel1.setPreferredSize(new java.awt.Dimension(1054, 96));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jurilogoAdvogado.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(1054, 433));

        lblNomeAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNomeAdv.setText("Nome Completo");

        txtNomeAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNomeAdv.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNomeAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeAdvActionPerformed(evt);
            }
        });

        lblSexoAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSexoAdv.setText("Sexo");

        lblNascAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNascAdv.setText("Data de Nascimento");

        try {
            txtNascAdv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNascAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNascAdv.setPreferredSize(new java.awt.Dimension(38, 20));
        txtNascAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNascAdvActionPerformed(evt);
            }
        });

        lblEstCivilAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEstCivilAdv.setText("Estado Civil");

        cmbEstCivilAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbEstCivilAdv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)" }));

        lblCPFAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCPFAdv.setText("CPF");

        try {
            txtCPFAdv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCPFAdv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFAdvFocusLost(evt);
            }
        });
        txtCPFAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFAdvActionPerformed(evt);
            }
        });

        lblRGAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRGAdv.setText("RG");

        txtRGAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblRendaFamiliarAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRendaFamiliarAdv.setText("Renda Familiar");

        lblCNHAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCNHAdv.setText("CNH");

        txtCNHAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtNaturalidadeAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNaturalidadeAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNaturalidadeAdvActionPerformed(evt);
            }
        });

        lblNaturalidadeAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNaturalidadeAdv.setText("Naturalidade");

        txtNacionalidadeAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblNacionalidadeAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNacionalidadeAdv.setText("Nacionalidade");

        lblTelefoneAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTelefoneAdv.setText("Telefone");

        try {
            txtTelefoneAdv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelefoneAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneAdvActionPerformed(evt);
            }
        });

        lblTelefone2Adv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTelefone2Adv.setText("Telefone 2");

        try {
            txtTelefone2Adv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone2Adv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelefone2Adv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefone2AdvActionPerformed(evt);
            }
        });

        lblEmailAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmailAdv.setText("E-mail");

        txtEmailAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblDataCadastroAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDataCadastroAdv.setText("Data de Cadastro");

        try {
            txtDataCadastroAdv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataCadastroAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblDadosAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDadosAdv.setText("DADOS DO ADVOGADO");

        lblEnderecoAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEnderecoAdv.setText("ENDEREÇO");

        lblRuaEnd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRuaEnd.setText("Logradouro");

        txtRuaEnd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtRuaEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaEndActionPerformed(evt);
            }
        });

        lblNumeroEnd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNumeroEnd.setText("Nº");

        txtNumeroEnd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumeroEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroEndActionPerformed(evt);
            }
        });

        lblBairroEnd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBairroEnd.setText("Bairro");

        txtBairroEnd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblUFEnd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUFEnd.setText("UF");

        cmbUFEnd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbUFEnd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cmbUFEnd.setAutoscrolls(true);

        lblCidadeEnd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCidadeEnd.setText("Cidade");

        btnInserir.setBackground(new java.awt.Color(255, 255, 255));
        btnInserir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInserir.setText("INSERIR");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        cmbSexoAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbSexoAdv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));
        cmbSexoAdv.setMinimumSize(new java.awt.Dimension(33, 18));
        cmbSexoAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSexoAdvActionPerformed(evt);
            }
        });

        txtCidadeEnd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCidadeEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeEndActionPerformed(evt);
            }
        });

        txtRendaFamiliarAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRendaFamiliarAdvActionPerformed(evt);
            }
        });

        lblOAB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOAB.setText("OAB");

        lblInscricaoAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblInscricaoAdv.setText("Inscrição");

        lblLetraAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblLetraAdv.setText("Letra");

        lblSecAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSecAdv.setText("Seccional");

        lblTipoInscAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTipoInscAdv.setText("Tipo de Inscrição");

        lblDataInscricaoOABAdv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDataInscricaoOABAdv.setText("Data de Inscrição na OAB");

        cmbSecAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbSecAdv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cmbSecAdv.setAutoscrolls(true);
        cmbSecAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSecAdvActionPerformed(evt);
            }
        });

        txtInscricaoAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInscricaoAdvActionPerformed(evt);
            }
        });

        cmbLetraAdv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não sei", "A", "B", "E", "N", "E" }));

        cmbTipoInscAdv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Advogado", "Estagiário", "Suplementar" }));
        cmbTipoInscAdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoInscAdvActionPerformed(evt);
            }
        });

        try {
            txtDataInscricaoOABAdv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataInscricaoOABAdv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtNomeAdv)
                        .addGap(30, 30, 30)
                        .addComponent(cmbSexoAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txtNascAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cmbEstCivilAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtRendaFamiliarAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(lblDadosAdv))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(lblNomeAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(250, 250, 250)
                            .addComponent(lblSexoAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63)
                            .addComponent(lblNascAdv)
                            .addGap(30, 30, 30)
                            .addComponent(lblEstCivilAdv)
                            .addGap(65, 65, 65)
                            .addComponent(lblRendaFamiliarAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(lblCPFAdv)
                            .addGap(155, 155, 155)
                            .addComponent(lblRGAdv)
                            .addGap(131, 131, 131)
                            .addComponent(lblCNHAdv)
                            .addGap(121, 121, 121)
                            .addComponent(lblNaturalidadeAdv)
                            .addGap(258, 258, 258)
                            .addComponent(lblNacionalidadeAdv))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(txtCPFAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(txtRGAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(txtCNHAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(txtNaturalidadeAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(txtNacionalidadeAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(lblTelefoneAdv)
                            .addGap(89, 89, 89)
                            .addComponent(lblTelefone2Adv)
                            .addGap(91, 91, 91)
                            .addComponent(lblEmailAdv)
                            .addGap(260, 260, 260)
                            .addComponent(lblDataCadastroAdv))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(txtTelefoneAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(txtTelefone2Adv, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(txtEmailAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(txtDataCadastroAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(lblEnderecoAdv))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtRuaEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblRuaEnd)
                                        .addComponent(lblOAB))
                                    .addGap(46, 46, 46)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lblNumeroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(86, 86, 86)
                                            .addComponent(lblBairroEnd)
                                            .addGap(283, 283, 283)
                                            .addComponent(lblUFEnd)
                                            .addGap(69, 69, 69)
                                            .addComponent(lblCidadeEnd))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(txtNumeroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(39, 39, 39)
                                            .addComponent(txtBairroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(35, 35, 35)
                                            .addComponent(cmbUFEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(31, 31, 31)
                                            .addComponent(txtCidadeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblInscricaoAdv)
                                        .addComponent(txtInscricaoAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(47, 47, 47)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(lblLetraAdv)
                                            .addGap(91, 91, 91))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(cmbLetraAdv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(21, 21, 21)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSecAdv)
                                        .addComponent(cmbSecAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(59, 59, 59)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblTipoInscAdv)
                                        .addComponent(cmbTipoInscAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(326, 326, 326)
                            .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDataInscricaoOABAdv)
                                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDataInscricaoOABAdv, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblDadosAdv)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeAdv)
                    .addComponent(lblSexoAdv)
                    .addComponent(lblNascAdv)
                    .addComponent(lblEstCivilAdv)
                    .addComponent(lblRendaFamiliarAdv))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeAdv)
                    .addComponent(cmbSexoAdv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbEstCivilAdv)
                    .addComponent(txtRendaFamiliarAdv)
                    .addComponent(txtNascAdv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPFAdv)
                    .addComponent(lblRGAdv)
                    .addComponent(lblCNHAdv)
                    .addComponent(lblNaturalidadeAdv)
                    .addComponent(lblNacionalidadeAdv))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCPFAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRGAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCNHAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNaturalidadeAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNacionalidadeAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefoneAdv)
                    .addComponent(lblTelefone2Adv)
                    .addComponent(lblEmailAdv)
                    .addComponent(lblDataCadastroAdv))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefoneAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone2Adv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataCadastroAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(lblEnderecoAdv)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRuaEnd)
                    .addComponent(lblNumeroEnd)
                    .addComponent(lblBairroEnd)
                    .addComponent(lblUFEnd)
                    .addComponent(lblCidadeEnd))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRuaEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbUFEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidadeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblOAB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInscricaoAdv)
                    .addComponent(lblLetraAdv)
                    .addComponent(lblSecAdv)
                    .addComponent(lblTipoInscAdv)
                    .addComponent(lblDataInscricaoOABAdv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSecAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInscricaoAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLetraAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoInscAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataInscricaoOABAdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInserir)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeAdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeAdvActionPerformed

    private void txtNaturalidadeAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNaturalidadeAdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNaturalidadeAdvActionPerformed

    private void txtTelefoneAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneAdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneAdvActionPerformed

    private void txtTelefone2AdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefone2AdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefone2AdvActionPerformed

    private void txtRuaEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaEndActionPerformed

    private void txtNumeroEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroEndActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
             
        txtNacionalidadeAdv.setEditable(true);
        txtNascAdv.setEditable(true);
        txtNaturalidadeAdv.setEditable(true);
        txtNomeAdv.setEditable(true);
        txtNumeroEnd.setEditable(true);
        txtBairroEnd.setEditable(true);
        txtTelefone2Adv.setEditable(true);
        txtTelefoneAdv.setEditable(true);
        txtEmailAdv.setEditable(true);
        txtCPFAdv.setEditable(true);
        txtRGAdv.setEditable(true);
        txtCNHAdv.setEditable(true);
        txtRendaFamiliarAdv.setEditable(true);
        txtRuaEnd.setEditable(true);
        txtDataCadastroAdv.setEditable(true);
        txtCidadeEnd.setEditable(true);
        txtInscricaoAdv.setEditable(true);
        txtDataInscricaoOABAdv.setEditable(true);
        cmbEstCivilAdv.setEditable(true);
        cmbSexoAdv.setEditable(true);
        cmbUFEnd.setEditable(true);
        cmbSecAdv.setEditable(true);
        cmbLetraAdv.setEditable(true);
        cmbTipoInscAdv.setEditable(true);

        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnInserir.setEnabled(false);
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        travarComponentes();
        btnInserir.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed

        Advogados adv = new Advogados();
        Endereco end = new Endereco();
        AdvogadoEndereco ae = new AdvogadoEndereco();
        AdvogadosDAO advDAO = new AdvogadosDAO();
        EnderecoDAO endDAO  = new EnderecoDAO();
        AdvogadoEnderecoDAO aeDAO = new AdvogadoEnderecoDAO();
        
        adv.setNomeAdv(txtNomeAdv.getText());
        adv.setSexoAdv(String.valueOf(cmbSexoAdv.getSelectedItem()));           
        adv.setEstadoCivilAdv(String.valueOf(cmbEstCivilAdv.getSelectedItem()));
        adv.setNaturalidadeAdv(txtNaturalidadeAdv.getText());
        adv.setNacionalidadeAdv(txtNacionalidadeAdv.getText());
        adv.setCpfAdv(txtCPFAdv.getText());
        adv.setRgAdv(txtRGAdv.getText());
        adv.setTelefoneAdv(txtTelefoneAdv.getText());
        adv.setTelefone2Adv(txtTelefone2Adv.getText());
        adv.setEmailAdv(txtEmailAdv.getText());
        adv.setCnhAdv(txtCNHAdv.getText());
        adv.setDataNascAdv(txtNascAdv.getText());
        adv.setDataCadastroAdv(txtDataCadastroAdv.getText());
        adv.setDataInsOAB(txtDataInscricaoOABAdv.getText());
        adv.setTipoInsAdv(String.valueOf(cmbTipoInscAdv.getSelectedItem()));
        adv.setSeccionalAdv(String.valueOf(cmbSecAdv.getSelectedItem()));
        adv.setLetraAdv(String.valueOf(cmbLetraAdv.getSelectedItem()));
        adv.setInscricaoAdv(txtInscricaoAdv.getText());
        adv.setRendaAdv(txtRendaFamiliarAdv.getText());
        
        
      
        end.setBairroEnd(txtBairroEnd.getText());
        end.setRuaEnd(txtRuaEnd.getText());
        end.setNumeroEnd(txtNumeroEnd.getText());
        end.setCidadeEnd(txtCidadeEnd.getText());
        end.setUfEnd(String.valueOf(cmbUFEnd.getSelectedItem()));

        advDAO.cadastrarAdvogados(adv);
        endDAO.cadastrarEndereco(end);

        ae.setCodAdv(advDAO.carregarCodAdv());
        ae.setCodEnd(endDAO.carregarCodEnd());
        aeDAO.vincularAdvogadoEndereco(ae);

        btnInserir.setEnabled(true);
        travarComponentes();

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void cmbSexoAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSexoAdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSexoAdvActionPerformed

    private void txtCidadeEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeEndActionPerformed

    private void txtRendaFamiliarAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRendaFamiliarAdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRendaFamiliarAdvActionPerformed

    private void txtNascAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNascAdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNascAdvActionPerformed

    private void cmbSecAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSecAdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSecAdvActionPerformed

    private void cmbTipoInscAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoInscAdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoInscAdvActionPerformed

    private void txtInscricaoAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInscricaoAdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInscricaoAdvActionPerformed

    private void txtCPFAdvFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFAdvFocusLost
        Mensagens m = new Mensagens("JuriSoft");
        ValidarCPF v = new ValidarCPF();
        if (!v.verificarCPF(txtCPFAdv.getText())){
            m.alerta("CPF inválido!");
            txtCPFAdv.setText(null);
            txtCPFAdv.requestFocus();
        }
    }//GEN-LAST:event_txtCPFAdvFocusLost

    private void txtCPFAdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFAdvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFAdvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarAdvogado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarAdvogado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarAdvogado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarAdvogado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormCadastrarAdvogado dialog = new FormCadastrarAdvogado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cmbEstCivilAdv;
    private javax.swing.JComboBox<String> cmbLetraAdv;
    private javax.swing.JComboBox cmbSecAdv;
    private javax.swing.JComboBox cmbSexoAdv;
    private javax.swing.JComboBox<String> cmbTipoInscAdv;
    private javax.swing.JComboBox cmbUFEnd;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBairroEnd;
    private javax.swing.JLabel lblCNHAdv;
    private javax.swing.JLabel lblCPFAdv;
    private javax.swing.JLabel lblCidadeEnd;
    private javax.swing.JLabel lblDadosAdv;
    private javax.swing.JLabel lblDataCadastroAdv;
    private javax.swing.JLabel lblDataInscricaoOABAdv;
    private javax.swing.JLabel lblEmailAdv;
    private javax.swing.JLabel lblEnderecoAdv;
    private javax.swing.JLabel lblEstCivilAdv;
    private javax.swing.JLabel lblInscricaoAdv;
    private javax.swing.JLabel lblLetraAdv;
    private javax.swing.JLabel lblNacionalidadeAdv;
    private javax.swing.JLabel lblNascAdv;
    private javax.swing.JLabel lblNaturalidadeAdv;
    private javax.swing.JLabel lblNomeAdv;
    private javax.swing.JLabel lblNumeroEnd;
    private javax.swing.JLabel lblOAB;
    private javax.swing.JLabel lblRGAdv;
    private javax.swing.JLabel lblRendaFamiliarAdv;
    private javax.swing.JLabel lblRuaEnd;
    private javax.swing.JLabel lblSecAdv;
    private javax.swing.JLabel lblSexoAdv;
    private javax.swing.JLabel lblTelefone2Adv;
    private javax.swing.JLabel lblTelefoneAdv;
    private javax.swing.JLabel lblTipoInscAdv;
    private javax.swing.JLabel lblUFEnd;
    private javax.swing.JTextField txtBairroEnd;
    private javax.swing.JTextField txtCNHAdv;
    private javax.swing.JFormattedTextField txtCPFAdv;
    private javax.swing.JTextField txtCidadeEnd;
    private javax.swing.JFormattedTextField txtDataCadastroAdv;
    private javax.swing.JFormattedTextField txtDataInscricaoOABAdv;
    private javax.swing.JTextField txtEmailAdv;
    private javax.swing.JTextField txtInscricaoAdv;
    private javax.swing.JTextField txtNacionalidadeAdv;
    private javax.swing.JFormattedTextField txtNascAdv;
    private javax.swing.JTextField txtNaturalidadeAdv;
    private javax.swing.JTextField txtNomeAdv;
    private javax.swing.JTextField txtNumeroEnd;
    private javax.swing.JTextField txtRGAdv;
    private javax.swing.JTextField txtRendaFamiliarAdv;
    private javax.swing.JTextField txtRuaEnd;
    private javax.swing.JFormattedTextField txtTelefone2Adv;
    private javax.swing.JFormattedTextField txtTelefoneAdv;
    // End of variables declaration//GEN-END:variables
    
    public void travarComponentes(){
    txtNacionalidadeAdv.setText(null);
    txtNascAdv.setText(null);
    txtNaturalidadeAdv.setText(null); 
    txtNomeAdv.setText(null);
    txtNumeroEnd.setText(null);
    txtBairroEnd.setText(null);
    txtTelefone2Adv.setText(null);
    txtTelefoneAdv.setText(null);
    txtEmailAdv.setText(null);
    txtCPFAdv.setText(null);
    txtRGAdv.setText(null);
    txtCNHAdv.setText(null);
    txtRendaFamiliarAdv.setText(null);
    txtRuaEnd.setText(null);
    txtDataCadastroAdv.setText(null);
    txtCidadeEnd.setText(null);
    txtInscricaoAdv.setText(null);
    txtDataInscricaoOABAdv.setText(null);
    cmbEstCivilAdv.setSelectedIndex(0);
    cmbSexoAdv.setSelectedIndex(0);
    cmbUFEnd.setSelectedIndex(0);
    cmbSecAdv.setSelectedIndex(0);
    cmbLetraAdv.setSelectedIndex(0);
    cmbTipoInscAdv.setSelectedIndex(0);
    
    

    
    txtNacionalidadeAdv.setEditable(false);
    txtNascAdv.setEditable(false);
    txtNaturalidadeAdv.setEditable(false);
    txtNomeAdv.setEditable(false);
    txtNumeroEnd.setEditable(false);
    txtBairroEnd.setEditable(false);
    txtTelefone2Adv.setEditable(false);
    txtTelefoneAdv.setEditable(false);
    txtEmailAdv.setEditable(false);
    txtCPFAdv.setEditable(false);
    txtRGAdv.setEditable(false);
    txtCNHAdv.setEditable(false);
    txtRendaFamiliarAdv.setEditable(false);
    txtRuaEnd.setEditable(false);
    txtDataCadastroAdv.setEditable(false);
    txtCidadeEnd.setEditable(false);
    txtInscricaoAdv.setEditable(false);
    txtDataInscricaoOABAdv.setEditable(false);
    cmbEstCivilAdv.setEditable(false);
    cmbSexoAdv.setEditable(false);
    cmbUFEnd.setEditable(false);
    cmbSecAdv.setEditable(false);
    cmbLetraAdv.setEditable(false);
    cmbTipoInscAdv.setEditable(false);

    btnCancelar.setEnabled(false);
    btnSalvar.setEnabled(false);
    }
}
