/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;
import dao.ClientesDAO;
import regrasDeNegocio.Clientes;
import regrasDeNegocio.Numeros;
import regrasDeNegocio.Letras;
import dao.EnderecoDAO;
import regrasDeNegocio.Endereco;
import dao.ClienteEnderecoDAO;
import java.util.ArrayList;
import javax.swing.JTextField;
import jurisoft.Mensagens;
import regrasDeNegocio.ClienteEndereco;
import regrasDeNegocio.ValidarCPF;
/**
 *
 * @author Paula Loeblein
 */
public class FormCadastrarClientes extends javax.swing.JDialog {
         
    /**
     * Creates new form Formulario
     */
    private ArrayList<JTextField> textFields = new ArrayList();
    
    public FormCadastrarClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        travarComponentes();
        
        txtNumeroEnd.setDocument(new Numeros());
        //txtCPFCli.setDocument(new Numeros());
        txtCNHCli.setDocument(new Numeros());
        txtNomeCli.setDocument(new Letras());
        txtPaiCli.setDocument(new Letras());
        txtMaeCli.setDocument(new Letras());
        txtNaturalidadeCli.setDocument(new Letras());
        txtNacionalidadeCli.setDocument(new Letras());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgCadastrarCli = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblNomeCli = new javax.swing.JLabel();
        txtNomeCli = new javax.swing.JTextField();
        lblSexoCli = new javax.swing.JLabel();
        lblNascCli = new javax.swing.JLabel();
        txtNascCli = new javax.swing.JFormattedTextField();
        lblEstCivilCli = new javax.swing.JLabel();
        cmbEstCivilCli = new javax.swing.JComboBox();
        lblCPFCli = new javax.swing.JLabel();
        txtCPFCli = new javax.swing.JFormattedTextField();
        lblRGCli = new javax.swing.JLabel();
        txtRGCli = new javax.swing.JTextField();
        lblRendaFamiliarCli = new javax.swing.JLabel();
        lblCNHCli = new javax.swing.JLabel();
        txtCNHCli = new javax.swing.JTextField();
        txtNaturalidadeCli = new javax.swing.JTextField();
        lblNaturalidadeCli = new javax.swing.JLabel();
        txtNacionalidadeCli = new javax.swing.JTextField();
        lblNacionalidadeCli = new javax.swing.JLabel();
        lblTelefoneCli = new javax.swing.JLabel();
        txtTelefoneCli = new javax.swing.JFormattedTextField();
        lblTelefone2Cli = new javax.swing.JLabel();
        txtTelefone2Cli = new javax.swing.JFormattedTextField();
        lblEmailCli = new javax.swing.JLabel();
        txtEmailCli = new javax.swing.JTextField();
        lblDataCadastroCli = new javax.swing.JLabel();
        txtDataCadastroCli = new javax.swing.JFormattedTextField();
        lblDadosCli = new javax.swing.JLabel();
        lblEnderecoCli = new javax.swing.JLabel();
        lblRuaEnd = new javax.swing.JLabel();
        txtRuaEnd = new javax.swing.JTextField();
        lblNumeroEnd = new javax.swing.JLabel();
        txtNumeroEnd = new javax.swing.JTextField();
        lblBairroEnd = new javax.swing.JLabel();
        txtBairroEnd = new javax.swing.JTextField();
        lblUFEnd = new javax.swing.JLabel();
        cmbUFEnd = new javax.swing.JComboBox();
        lblCidadeEnd = new javax.swing.JLabel();
        lblPaiCli = new javax.swing.JLabel();
        lblFiliacaoCli = new javax.swing.JLabel();
        lblMaeCli = new javax.swing.JLabel();
        txtMaeCli = new javax.swing.JTextField();
        txtPaiCli = new javax.swing.JTextField();
        btnInserir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        cmbSexoCli = new javax.swing.JComboBox();
        txtCidadeEnd = new javax.swing.JTextField();
        txtRendaFamiliarCli = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Cliente");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgCadastrarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jurilogoCliente.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgCadastrarCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgCadastrarCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1054, 500));

        lblNomeCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNomeCli.setText("Nome Completo");

        txtNomeCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNomeCli.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNomeCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeCliActionPerformed(evt);
            }
        });

        lblSexoCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSexoCli.setText("Sexo");

        lblNascCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNascCli.setText("Data de Nascimento");

        try {
            txtNascCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNascCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNascCli.setPreferredSize(new java.awt.Dimension(38, 20));

        lblEstCivilCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEstCivilCli.setText("Estado Civil");

        cmbEstCivilCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbEstCivilCli.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro(a)", "Casado(a)", "Divorciado(a)", "Viúvo(a)" }));

        lblCPFCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCPFCli.setText("CPF");

        try {
            txtCPFCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPFCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCPFCli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCPFCliFocusLost(evt);
            }
        });

        lblRGCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRGCli.setText("RG");

        txtRGCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblRendaFamiliarCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRendaFamiliarCli.setText("Renda Familiar");

        lblCNHCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCNHCli.setText("CNH");

        txtCNHCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtNaturalidadeCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNaturalidadeCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNaturalidadeCliActionPerformed(evt);
            }
        });

        lblNaturalidadeCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNaturalidadeCli.setText("Naturalidade");

        txtNacionalidadeCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblNacionalidadeCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNacionalidadeCli.setText("Nacionalidade");

        lblTelefoneCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTelefoneCli.setText("Telefone");

        try {
            txtTelefoneCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefoneCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelefoneCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefoneCliActionPerformed(evt);
            }
        });

        lblTelefone2Cli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTelefone2Cli.setText("Telefone 2");

        try {
            txtTelefone2Cli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone2Cli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelefone2Cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefone2CliActionPerformed(evt);
            }
        });

        lblEmailCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmailCli.setText("E-mail");

        txtEmailCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblDataCadastroCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDataCadastroCli.setText("Data de Cadastro");

        try {
            txtDataCadastroCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataCadastroCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblDadosCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDadosCli.setText("DADOS DO CLIENTE");

        lblEnderecoCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEnderecoCli.setText("ENDEREÇO");

        lblRuaEnd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRuaEnd.setText("Logradouro");

        txtRuaEnd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtRuaEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaEndActionPerformed(evt);
            }
        });

        lblNumeroEnd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNumeroEnd.setText("Nº");

        txtNumeroEnd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumeroEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroEndActionPerformed(evt);
            }
        });

        lblBairroEnd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBairroEnd.setText("Bairro");

        txtBairroEnd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        lblUFEnd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUFEnd.setText("UF");

        cmbUFEnd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbUFEnd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cmbUFEnd.setAutoscrolls(true);

        lblCidadeEnd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCidadeEnd.setText("Cidade");

        lblPaiCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPaiCli.setText("Pai");

        lblFiliacaoCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFiliacaoCli.setText("FILIAÇÃO");

        lblMaeCli.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMaeCli.setText("Mãe");

        txtMaeCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtPaiCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnInserir.setBackground(new java.awt.Color(255, 255, 255));
        btnInserir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInserir.setText("INSERIR");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        cmbSexoCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbSexoCli.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));
        cmbSexoCli.setMinimumSize(new java.awt.Dimension(33, 18));
        cmbSexoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSexoCliActionPerformed(evt);
            }
        });

        txtCidadeEnd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCidadeEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeEndActionPerformed(evt);
            }
        });

        txtRendaFamiliarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRendaFamiliarCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtNomeCli)
                        .addGap(30, 30, 30)
                        .addComponent(cmbSexoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(txtNascCli, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(cmbEstCivilCli, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtRendaFamiliarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(lblDadosCli))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(lblNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(250, 250, 250)
                            .addComponent(lblSexoCli, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63)
                            .addComponent(lblNascCli)
                            .addGap(30, 30, 30)
                            .addComponent(lblEstCivilCli)
                            .addGap(65, 65, 65)
                            .addComponent(lblRendaFamiliarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(lblCPFCli)
                            .addGap(155, 155, 155)
                            .addComponent(lblRGCli)
                            .addGap(131, 131, 131)
                            .addComponent(lblCNHCli)
                            .addGap(121, 121, 121)
                            .addComponent(lblNaturalidadeCli)
                            .addGap(258, 258, 258)
                            .addComponent(lblNacionalidadeCli))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(txtCPFCli, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(txtRGCli, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(37, 37, 37)
                            .addComponent(txtCNHCli, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(txtNaturalidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(31, 31, 31)
                            .addComponent(txtNacionalidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(lblTelefoneCli)
                            .addGap(89, 89, 89)
                            .addComponent(lblTelefone2Cli)
                            .addGap(91, 91, 91)
                            .addComponent(lblEmailCli)
                            .addGap(260, 260, 260)
                            .addComponent(lblDataCadastroCli))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(txtTelefoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(txtTelefone2Cli, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(txtEmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(41, 41, 41)
                            .addComponent(txtDataCadastroCli, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(lblEnderecoCli))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(lblFiliacaoCli))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(lblPaiCli)
                            .addGap(381, 381, 381)
                            .addComponent(lblMaeCli))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(txtPaiCli, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(39, 39, 39)
                            .addComponent(txtMaeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(326, 326, 326)
                            .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(51, 51, 51)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtRuaEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblRuaEnd))
                            .addGap(46, 46, 46)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(lblNumeroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(86, 86, 86)
                                    .addComponent(lblBairroEnd)
                                    .addGap(283, 283, 283)
                                    .addComponent(lblUFEnd)
                                    .addGap(69, 69, 69)
                                    .addComponent(lblCidadeEnd))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtNumeroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(39, 39, 39)
                                    .addComponent(txtBairroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(cmbUFEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(txtCidadeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblDadosCli)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeCli)
                    .addComponent(lblSexoCli)
                    .addComponent(lblNascCli)
                    .addComponent(lblEstCivilCli)
                    .addComponent(lblRendaFamiliarCli))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeCli)
                    .addComponent(cmbSexoCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbEstCivilCli)
                    .addComponent(txtRendaFamiliarCli)
                    .addComponent(txtNascCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPFCli)
                    .addComponent(lblRGCli)
                    .addComponent(lblCNHCli)
                    .addComponent(lblNaturalidadeCli)
                    .addComponent(lblNacionalidadeCli))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCPFCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRGCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCNHCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNaturalidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNacionalidadeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelefoneCli)
                    .addComponent(lblTelefone2Cli)
                    .addComponent(lblEmailCli)
                    .addComponent(lblDataCadastroCli))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefoneCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone2Cli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataCadastroCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(lblEnderecoCli)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRuaEnd)
                    .addComponent(lblNumeroEnd)
                    .addComponent(lblBairroEnd)
                    .addComponent(lblUFEnd)
                    .addComponent(lblCidadeEnd))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRuaEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBairroEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbUFEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidadeEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(lblFiliacaoCli)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPaiCli)
                    .addComponent(lblMaeCli))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPaiCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInserir)
                    .addComponent(btnCancelar)
                    .addComponent(btnSalvar)))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 1054, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeCliActionPerformed

    private void txtNaturalidadeCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNaturalidadeCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNaturalidadeCliActionPerformed

    private void txtTelefone2CliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefone2CliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefone2CliActionPerformed

    private void txtRuaEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaEndActionPerformed

    private void txtNumeroEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroEndActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        travarComponentes();
        btnInserir.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        
        Clientes cliente = new Clientes();
        Endereco endereco = new Endereco();
        ClienteEndereco ce = new ClienteEndereco();
        ClientesDAO cliDAO = new ClientesDAO();
        EnderecoDAO endDAO  = new EnderecoDAO();
        ClienteEnderecoDAO ceDAO = new ClienteEnderecoDAO();
        
        cliente.setNomeCli(txtNomeCli.getText());
        cliente.setSexoCli(String.valueOf(cmbSexoCli.getSelectedItem()));
        cliente.setRendaCli(txtRendaFamiliarCli.getText());
        cliente.setRgCli(txtRGCli.getText());
        cliente.setEstadoCivilCli(String.valueOf(cmbEstCivilCli.getSelectedItem()));
        cliente.setNaturalidadeCli(txtNaturalidadeCli.getText());
        cliente.setNacionalidadeCli(txtNacionalidadeCli.getText());
        cliente.setFiliacaoPaiCli(txtPaiCli.getText());
        cliente.setFiliacaoMaeCli(txtMaeCli.getText());
        cliente.setCpfCli(txtCPFCli.getText());
        cliente.setTelefoneCli(txtTelefoneCli.getText());
        cliente.setTelefone2Cli(txtTelefone2Cli.getText());
        cliente.setEmailCli(txtEmailCli.getText());
        cliente.setCnhCli(txtCNHCli.getText());
        cliente.setDataNascCli(txtNascCli.getText());
        cliente.setDataCadastroCli(txtDataCadastroCli.getText());
        
        endereco.setBairroEnd(txtBairroEnd.getText());
        endereco.setRuaEnd(txtRuaEnd.getText());
        endereco.setNumeroEnd(txtNumeroEnd.getText());
        endereco.setCidadeEnd(txtCidadeEnd.getText());
        endereco.setUfEnd(String.valueOf(cmbUFEnd.getSelectedItem()));

        cliDAO.cadastrarClientes(cliente);
        endDAO.cadastrarEndereco(endereco);
        
        ce.setCodCli(cliDAO.carregarCodCli());
        ce.setCodEnd(endDAO.carregarCodEnd());
        ceDAO.vincularClienteEndereco(ce);
      
        btnInserir.setEnabled(true);
        travarComponentes();
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        txtNomeCli.setEditable(true);
        txtCNHCli.setEditable(true);
        txtCPFCli.setEditable(true);
        txtRGCli.setEditable(true);
        txtDataCadastroCli.setEditable(true);
        txtNascCli.setEditable(true);
        txtPaiCli.setEditable(true);
        txtMaeCli.setEditable(true);
        txtRuaEnd.setEditable(true);
        txtRendaFamiliarCli.setEditable(true);
        txtNumeroEnd.setEditable(true);
        txtNaturalidadeCli.setEditable(true);
        txtNacionalidadeCli.setEditable(true);
        txtTelefone2Cli.setEditable(true);
        txtTelefoneCli.setEditable(true);
        txtEmailCli.setEditable(true);
        txtBairroEnd.setEditable(true);
        txtCidadeEnd.setEditable(true);
        cmbEstCivilCli.setEditable(true);
        cmbSexoCli.setEditable(true);
        cmbUFEnd.setEditable(true);

        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnInserir.setEnabled(false);
    }//GEN-LAST:event_btnInserirActionPerformed

    private void txtTelefoneCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefoneCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefoneCliActionPerformed

    private void cmbSexoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSexoCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSexoCliActionPerformed

    private void txtCidadeEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeEndActionPerformed

    private void txtRendaFamiliarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRendaFamiliarCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRendaFamiliarCliActionPerformed

    private void txtCPFCliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCPFCliFocusLost
        Mensagens m = new Mensagens("JuriSoft");
        ValidarCPF v = new ValidarCPF();
        if (!v.verificarCPF(txtCPFCli.getText())){
            m.alerta("CPF inválido!");
            txtCPFCli.setText(null);
            txtCPFCli.requestFocus();
        }
    }//GEN-LAST:event_txtCPFCliFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormCadastrarClientes dialog = new FormCadastrarClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cmbEstCivilCli;
    private javax.swing.JComboBox cmbSexoCli;
    private javax.swing.JComboBox cmbUFEnd;
    private javax.swing.JLabel imgCadastrarCli;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBairroEnd;
    private javax.swing.JLabel lblCNHCli;
    private javax.swing.JLabel lblCPFCli;
    private javax.swing.JLabel lblCidadeEnd;
    private javax.swing.JLabel lblDadosCli;
    private javax.swing.JLabel lblDataCadastroCli;
    private javax.swing.JLabel lblEmailCli;
    private javax.swing.JLabel lblEnderecoCli;
    private javax.swing.JLabel lblEstCivilCli;
    private javax.swing.JLabel lblFiliacaoCli;
    private javax.swing.JLabel lblMaeCli;
    private javax.swing.JLabel lblNacionalidadeCli;
    private javax.swing.JLabel lblNascCli;
    private javax.swing.JLabel lblNaturalidadeCli;
    private javax.swing.JLabel lblNomeCli;
    private javax.swing.JLabel lblNumeroEnd;
    private javax.swing.JLabel lblPaiCli;
    private javax.swing.JLabel lblRGCli;
    private javax.swing.JLabel lblRendaFamiliarCli;
    private javax.swing.JLabel lblRuaEnd;
    private javax.swing.JLabel lblSexoCli;
    private javax.swing.JLabel lblTelefone2Cli;
    private javax.swing.JLabel lblTelefoneCli;
    private javax.swing.JLabel lblUFEnd;
    private javax.swing.JTextField txtBairroEnd;
    private javax.swing.JTextField txtCNHCli;
    private javax.swing.JFormattedTextField txtCPFCli;
    private javax.swing.JTextField txtCidadeEnd;
    private javax.swing.JFormattedTextField txtDataCadastroCli;
    private javax.swing.JTextField txtEmailCli;
    private javax.swing.JTextField txtMaeCli;
    private javax.swing.JTextField txtNacionalidadeCli;
    private javax.swing.JFormattedTextField txtNascCli;
    private javax.swing.JTextField txtNaturalidadeCli;
    private javax.swing.JTextField txtNomeCli;
    private javax.swing.JTextField txtNumeroEnd;
    private javax.swing.JTextField txtPaiCli;
    private javax.swing.JTextField txtRGCli;
    private javax.swing.JTextField txtRendaFamiliarCli;
    private javax.swing.JTextField txtRuaEnd;
    private javax.swing.JFormattedTextField txtTelefone2Cli;
    private javax.swing.JFormattedTextField txtTelefoneCli;
    // End of variables declaration//GEN-END:variables

    public void travarComponentes(){
    txtNacionalidadeCli.setText(null);
    txtNascCli.setText(null);
    txtNaturalidadeCli.setText(null); 
    txtNomeCli.setText(null);
    txtNumeroEnd.setText(null);
    txtBairroEnd.setText(null);
    txtTelefone2Cli.setText(null);
    txtTelefoneCli.setText(null);
    txtEmailCli.setText(null);
    txtPaiCli.setText(null);
    txtMaeCli.setText(null);
    txtCPFCli.setText(null);
    txtRGCli.setText(null);
    txtCNHCli.setText(null);
    txtRendaFamiliarCli.setText(null);
    txtRuaEnd.setText(null);
    txtDataCadastroCli.setText(null);
    txtCidadeEnd.setText(null);
    cmbEstCivilCli.setSelectedIndex(0);
    cmbSexoCli.setSelectedIndex(0);
    cmbUFEnd.setSelectedIndex(0);
    
    
    txtNacionalidadeCli.setEditable(false);
    txtNascCli.setEditable(false);
    txtNaturalidadeCli.setEditable(false);
    txtNomeCli.setEditable(false);
    txtNumeroEnd.setEditable(false);
    txtBairroEnd.setEditable(false);
    txtTelefone2Cli.setEditable(false);
    txtTelefoneCli.setEditable(false);
    txtEmailCli.setEditable(false);
    txtPaiCli.setEditable(false);
    txtMaeCli.setEditable(false);
    txtCPFCli.setEditable(false);
    txtRGCli.setEditable(false);
    txtCNHCli.setEditable(false);
    txtRendaFamiliarCli.setEditable(false);
    txtRuaEnd.setEditable(false);
    txtDataCadastroCli.setEditable(false);
    txtCidadeEnd.setEditable(false);
    cmbEstCivilCli.setEditable(false);
    cmbSexoCli.setEditable(false);
    cmbUFEnd.setEditable(false);

    btnCancelar.setEnabled(false);
    btnSalvar.setEnabled(false);
    }
}
