/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

//import com.sun.xml.internal.ws.client.ContentNegotiation;
import dao.IntimacaoDAO;
import dao.ProcessoDAO;
import jurisoft.Mensagens;
import regrasDeNegocio.Intimacao;
import regrasDeNegocio.Processo;

/**
 *
 * @author Cliente
 */
public class FormCadastrarIntimacao extends javax.swing.JDialog {
    

    /**
     * Creates new form FormIntimacao
     */
    public FormCadastrarIntimacao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        travarComponentes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        txtDataCadastroCli = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblProcessoInt = new javax.swing.JLabel();
        lblDataAudInt = new javax.swing.JLabel();
        lblAtoInt = new javax.swing.JLabel();
        lblPrazoInt = new javax.swing.JLabel();
        lblResultadoInt = new javax.swing.JLabel();
        lblDataRecebimentoInt = new javax.swing.JLabel();
        lblDescricaoInt = new javax.swing.JLabel();
        lblNumeroInt = new javax.swing.JLabel();
        txtProcessoInt = new javax.swing.JTextField();
        txtAtoInt = new javax.swing.JTextField();
        txtResultadoInt = new javax.swing.JTextField();
        txtNumeroInt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        lblRascunhoInt = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRascunho = new javax.swing.JTextArea();
        btnInserir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtPrazoInt = new javax.swing.JFormattedTextField();
        txtDataAudInt = new javax.swing.JFormattedTextField();
        txtDataRecebimentoInt = new javax.swing.JFormattedTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        try {
            txtDataCadastroCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataCadastroCli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Cadastrar Intimação"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jurilogoIntimacao_1.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 96));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 96));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 96));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 500));

        lblProcessoInt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblProcessoInt.setText("Processo Vinculado:");

        lblDataAudInt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDataAudInt.setText("Data da Audiência:");

        lblAtoInt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAtoInt.setText("Ato Designado:");

        lblPrazoInt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPrazoInt.setText("Prazo Para Manifestação: ");

        lblResultadoInt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblResultadoInt.setText("Resultado:");

        lblDataRecebimentoInt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDataRecebimentoInt.setText("Data do Recebimento:");

        lblDescricaoInt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDescricaoInt.setText("Descrição:");

        lblNumeroInt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNumeroInt.setText("Número:");

        txtProcessoInt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtProcessoInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcessoIntActionPerformed(evt);
            }
        });

        txtAtoInt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAtoInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtoIntActionPerformed(evt);
            }
        });

        txtResultadoInt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtNumeroInt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNumeroInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroIntActionPerformed(evt);
            }
        });

        txtDescricao.setColumns(20);
        txtDescricao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        lblRascunhoInt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblRascunhoInt.setText("Rascunho:");

        txtRascunho.setColumns(20);
        txtRascunho.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtRascunho.setRows(5);
        jScrollPane2.setViewportView(txtRascunho);

        btnInserir.setBackground(new java.awt.Color(255, 255, 255));
        btnInserir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInserir.setText("INSERIR");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        try {
            txtPrazoInt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtPrazoInt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        try {
            txtDataAudInt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataAudInt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        try {
            txtDataRecebimentoInt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataRecebimentoInt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProcessoInt)
                                    .addComponent(txtProcessoInt, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDataAudInt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDataAudInt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblAtoInt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtAtoInt)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDescricaoInt)
                                .addGap(108, 108, 108))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrazoInt)
                                    .addComponent(txtPrazoInt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtResultadoInt)
                                        .addGap(28, 28, 28)
                                        .addComponent(txtDataRecebimentoInt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(142, 142, 142))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblResultadoInt)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblRascunhoInt))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDataRecebimentoInt, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumeroInt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNumeroInt)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnInserir)
                        .addGap(43, 43, 43)
                        .addComponent(btnCancelar)
                        .addGap(43, 43, 43)
                        .addComponent(btnSalvar)
                        .addGap(121, 121, 121)))
                .addGap(99, 99, 99))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProcessoInt)
                    .addComponent(lblDataAudInt)
                    .addComponent(lblAtoInt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProcessoInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAtoInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataAudInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrazoInt)
                            .addComponent(lblResultadoInt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrazoInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumeroInt)
                            .addComponent(lblDataRecebimentoInt, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeroInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDataRecebimentoInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtResultadoInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addComponent(lblDescricaoInt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRascunhoInt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnInserir))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 790, 520));

        getAccessibleContext().setAccessibleName("Cadastrar Intimação");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProcessoIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcessoIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProcessoIntActionPerformed

    private void txtNumeroIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroIntActionPerformed

    private void txtAtoIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtoIntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAtoIntActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        txtDataAudInt.setEditable(true);
        txtDataRecebimentoInt.setEditable(true);
        txtPrazoInt.setEditable(true);
        txtDescricao.setEditable(true);
        txtRascunho.setEditable(true);
        txtResultadoInt.setEditable(true);
        txtAtoInt.setEditable(true);
        txtNumeroInt.setEditable(true);
        txtProcessoInt.setEditable(true);

        btnCancelar.setEnabled(true);
        btnSalvar.setEnabled(true);
        btnInserir.setEnabled(false);
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        travarComponentes();
        btnInserir.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
      
        Processo proc = new Processo();
        ProcessoDAO procDAO = new ProcessoDAO();
        Intimacao inti = new Intimacao();
        IntimacaoDAO intiDAO = new IntimacaoDAO();
        
        
        procDAO.pesquisarNumeroPro(txtNumeroInt.getText());
        proc = procDAO.getProcesso();
        
        inti.setDataAudInt(txtDataAudInt.getText());
        inti.setDataRecebInt(txtDataRecebimentoInt.getText());           
        inti.setPrazoInt(txtPrazoInt.getText());
        inti.setDescricaoInt(txtDescricao.getText());
        inti.setRascunhoInt(txtRascunho.getText());
        inti.setResultado(txtResultadoInt.getText());
        inti.setAtoInt(txtAtoInt.getText());
        inti.setNumeroInt(txtNumeroInt.getText());
        inti.setProcessoInt(txtProcessoInt.getText());
        
        inti.setCodPro(proc.getCodPro());
        intiDAO.cadastrarIntimacao(inti);

        btnInserir.setEnabled(true);
        travarComponentes();

    }//GEN-LAST:event_btnSalvarActionPerformed
                                        

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarIntimacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarIntimacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarIntimacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarIntimacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormCadastrarIntimacao dialog = new FormCadastrarIntimacao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAtoInt;
    private javax.swing.JLabel lblDataAudInt;
    private javax.swing.JLabel lblDataRecebimentoInt;
    private javax.swing.JLabel lblDescricaoInt;
    private javax.swing.JLabel lblNumeroInt;
    private javax.swing.JLabel lblPrazoInt;
    private javax.swing.JLabel lblProcessoInt;
    private javax.swing.JLabel lblRascunhoInt;
    private javax.swing.JLabel lblResultadoInt;
    private javax.swing.JTextField txtAtoInt;
    private javax.swing.JFormattedTextField txtDataAudInt;
    private javax.swing.JFormattedTextField txtDataCadastroCli;
    private javax.swing.JFormattedTextField txtDataRecebimentoInt;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNumeroInt;
    private javax.swing.JFormattedTextField txtPrazoInt;
    private javax.swing.JTextField txtProcessoInt;
    private javax.swing.JTextArea txtRascunho;
    private javax.swing.JTextField txtResultadoInt;
    // End of variables declaration//GEN-END:variables
    public void travarComponentes(){
        txtDataAudInt.setText(null);
        txtDataRecebimentoInt.setText(null);
        txtPrazoInt.setText(null); 
        txtDescricao.setText(null);
        txtRascunho.setText(null);
        txtResultadoInt.setText(null);
        txtAtoInt.setText(null);
        txtNumeroInt.setText(null);
        txtProcessoInt.setText(null);
        
        txtDataAudInt.setEditable(false);
        txtDataRecebimentoInt.setEditable(false);
        txtPrazoInt.setEditable(false);
        txtDescricao.setEditable(false);
        txtRascunho.setEditable(false);
        txtResultadoInt.setEditable(false);
        txtAtoInt.setEditable(false);
        txtNumeroInt.setEditable(false);
        txtProcessoInt.setEditable(false);

        btnCancelar.setEnabled(false);
        btnSalvar.setEnabled(false);
    }
}
